on:
  issues:
    types:
      - labeled

jobs:
  issue_to_markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOOT }}
      - uses: eunjae-lee/issue-to-markdown@v1
        with:
          token: ${{ secrets.TOOT }}  
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update contents'
